// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRwblm3QBkN-tI7qrq9s64QSEPv4zjYI',
    appId: '1:34829389706:web:04e899f25380291770c273',
    messagingSenderId: '34829389706',
    projectId: 'shyamex-2059f',
    authDomain: 'shyamex-2059f.firebaseapp.com',
    storageBucket: 'shyamex-2059f.appspot.com',
    measurementId: 'G-D3BX7XS92C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw7YAoM61qLjg1qOiRaIVFaX6L3Q6rofg',
    appId: '1:34829389706:android:a458b39899a1d5c970c273',
    messagingSenderId: '34829389706',
    projectId: 'shyamex-2059f',
    storageBucket: 'shyamex-2059f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4sedBy5v5WbmDtBk2N0oT5wbd4NGY7Q',
    appId: '1:34829389706:ios:c1961dbdb911b39370c273',
    messagingSenderId: '34829389706',
    projectId: 'shyamex-2059f',
    storageBucket: 'shyamex-2059f.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4sedBy5v5WbmDtBk2N0oT5wbd4NGY7Q',
    appId: '1:34829389706:ios:c1961dbdb911b39370c273',
    messagingSenderId: '34829389706',
    projectId: 'shyamex-2059f',
    storageBucket: 'shyamex-2059f.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSRwblm3QBkN-tI7qrq9s64QSEPv4zjYI',
    appId: '1:34829389706:web:150a69a3820cf51c70c273',
    messagingSenderId: '34829389706',
    projectId: 'shyamex-2059f',
    authDomain: 'shyamex-2059f.firebaseapp.com',
    storageBucket: 'shyamex-2059f.appspot.com',
    measurementId: 'G-CM332G14F4',
  );
}
